### PR TITLE
Fix/react 15 5

### PR DESCRIPTION
**Pull request by Anomen**
For support of React 15.5:

 * Changed deprecated React.PropTypes to use `prop-types`
 * Changed deprecated React.createClass to ES6 class

### CODE REVIEW

**Comment by peterpme** [comment]
Wow @Anomen thank you so much for this awesome PR! I will help you push this along and merge it in :smile:

I haven't had a chance to test it myself locally - do all the tests continue to pass?

Thanks again!

**Comment by Anomen** [comment]
Hey @peterpme :) Yes, all the tests pass. The only thing that could be improved is to also change `React.createClass` inside the tests themselves, because it create a warning when running them (which does not make them fail, though).

I can try to fix them in the coming days ;)

**Comment by diondirza** [comment]
when will this PR be merged? any progress so far?

**Comment by peterpme** [comment]
@diondirza we can merge it in, just want to take care of the standalone.min.js conflict :)

**Comment by exwar** [comment]
@Anomen Any chance you can have a look at these conflicts and get this merged?

**Pull request merged**
