### PR TITLE
fix server render

### PR DESCRIPTION
**Pull request by alexeyMohnatkin**

### CODE REVIEW

**Comment by peterpme** [comment]
:wave: @alexeyMohnatkin! Do you mind adding tests that might affect these changes?

Thanks!

**Comment by alexeyMohnatkin** [comment]
Maybe later, now I don't have any free time

**Comment by alexeyMohnatkin** [comment]
added tests

**Comment by Akurganow** [comment]
Any progress with this PR?

**Comment by brtw** [comment]
@peterpme  Is there any intention to merge this in? Anything I can do to help?

**Comment by bnisbett** [comment]
@alexeyMohnatkin this was merged but not built so the Experiment.js file is out of date and doesn't have the correct changes. 
I did a quick PR to show the difference: https://github.com/pushtell/react-ab-test/pull/43

**Pull request merged**
