### PR TITLE
fixing memory leaks while server rendering

### PR DESCRIPTION
**Pull request by getahead**
This PR fixes memory leaks during server rendering https://github.com/pushtell/react-ab-test/issues/16
I've added .rewind() method to emitter to cleanup all the subscriptions. Calling this after ReactDOMServer.renderToString is preventing leaks (just like react-helmet)

### CODE REVIEW

**Comment by lauterry** [comment]
Hi

Can this pull request be merged please ?

Best regards

**Comment by peterpme** [comment]
:wave: anything I can do to help move this along?

**Comment by peterpme** [comment]
Hey @getahead thanks so much for the PR! Do you mind writing a test to accompany this? I'll test it on my own locally as well :smile:

**Comment by peterpme** [comment]
Thanks for the help @getahead!

I ran the current tests and everything was working so I'll be merging it in.

/cc @lauterry

**Pull request merged**
